### ISSUE TITLE
A few suggestions to CSS code.

### ISSUE THREAD

**Issue by josephtkim** [thunsber/teacozy#5]
There was a small syntax error on line 138 of the CSS code, which was missing a semi-colon. Make sure to end each line with a semi-colon, or there may be some unwanted issues with your page.

Another suggestion is to add descriptions above each section in the CSS code, similar to how you would for the HTML code. For instance,

```css
/* Contact Section */
.contact {
  width: 1200px;
}

/* Footer Section */
footer {
  text-align: left;
  padding-left: 20px;
}
```
